apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-certificates
# type: kubernetes.io/tls
data:
  cert.pem: |
    LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURrekNDQW51Z0F3SUJBZ0lVWFZZa1JDck0v
    Z2UwM0RWeW1EdFhDdXlicDdnd0RRWUpLb1pJaHZjTkFRRUwKQlFBd1dURUxNQWtHQTFVRUJoTUNW
    Vk14RXpBUkJnTlZCQWdNQ2xOdmJXVXRVM1JoZEdVeElUQWZCZ05WQkFvTQpHRWx1ZEdWeWJtVjBJ
    RmRwWkdkcGRITWdVSFI1SUV4MFpERVNNQkFHQTFVRUF3d0piRzlqWVd4b2IzTjBNQjRYCkRUSXhN
    RGN6TVRFME1qSXhNbG9YRFRJeU1EY3pNVEUwTWpJeE1sb3dXVEVMTUFrR0ExVUVCaE1DVlZNeEV6
    QVIKQmdOVkJBZ01DbE52YldVdFUzUmhkR1V4SVRBZkJnTlZCQW9NR0VsdWRHVnlibVYwSUZkcFpH
    ZHBkSE1nVUhSNQpJRXgwWkRFU01CQUdBMVVFQXd3SmJHOWpZV3hvYjNOME1JSUJJakFOQmdrcWhr
    aUc5dzBCQVFFRkFBT0NBUThBCk1JSUJDZ0tDQVFFQTAyVjVaam1xTEIvVlF3VGFycnovMzVxc2E4
    M0wrRGJBb2EwMDAxK2pWbW1DK0c5TnVmaTAKZGFyb0ZXai9VaWN2MmZaV0VUVThKb1pLVXJYNEJL
    OW9nNWNnNXJsbi9DdEJSV0NVWUl3UmdZOVIvQ2RCR1BuNAprcCtYa1NKYUN3NzRaSXlMeS9aZnV4
    Nmg4RVMxbTlZUm5CemErczdVK0ltUkJSZjRNUlB0WFEzL21xSnhBWllxCmRPbktudnNzUnlEMnF1
    dGdWVEF4d01VdkpXSWl2UmhSWURqN1dPcFM0Q0VFZVF4UDFpSDEvVDVQN0ZkdFRHZFQKYlZCQUJD
    QThKaEw5NnVGR1BwT1lIY00vN1I1RUlBM3laNUZOZzkzMVF6b0RJVGp0WEd0UTZ5OS9sL0lZa1dt
    NgpKNjdSV2NOMElvVHNaaHowV05VNGdBZXNsVnRKTG9mbjhRSURBUUFCbzFNd1VUQWRCZ05WSFE0
    RUZnUVV6Rm5LCk5mUzRMQVl1S2VXd0hiem9vRVIweVowd0h3WURWUjBqQkJnd0ZvQVV6Rm5LTmZT
    NExBWXVLZVd3SGJ6b29FUjAKeVowd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBTkJna3Foa2lHOXcw
    QkFRc0ZBQU9DQVFFQWs0TytlOWppYTU5Vwpad2V0TjRHVTdPV2NZaG1PZ1NpelJTczZ1N21UZnA2
    MkxETXQ5NldLVTNUSGtzT25aNDRIbnFXUXhzU2ZkRlZVClhKRDEydGp2VlU4WjRGV3pRYWpjSGVl
    bVVZaUR6ZThFQWg2VG54blVjT3JVOEljd2lLR3hDV1JZLzkwOGpuV2cKK01Nc2NmTUNNWVRSZGVU
    UHFEOGZHekFsVUN0bXl6SDZLTEUzczRPby9yNStOUitVdnJ3cGR2Yjd4ZTBNd3dPOQpRL3pSNE44
    ZXAvSHdIVkVPYmNhQm9mRTFzc1pMa3NYN1pnQ1A5d01nWFJXcE5BdEM1RVd4TWJ4WWpCZldGSDI0
    CmZESmxCTWlHSldnOEhIY3hLN3dRaEZoK2Z1eU56RSt4RVdQc0k5VkwxekRmdGQ5eDgvUXNPYWd5
    RU9uWThWeHIKQW9wdlowOXVFUT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  key.pem: |
    LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2UUlCQURBTkJna3Foa2lHOXcwQkFRRUZB
    QVNDQktjd2dnU2pBZ0VBQW9JQkFRRFRaWGxtT2Fvc0g5VkQKQk5xdXZQL2ZtcXhyemN2NE5zQ2hy
    VFRUWDZOV2FZTDRiMDI1K0xSMXF1Z1ZhUDlTSnkvWjlsWVJOVHdtaGtwUwp0ZmdFcjJpRGx5RG11
    V2Y4SzBGRllKUmdqQkdCajFIOEowRVkrZmlTbjVlUklsb0xEdmhrakl2TDlsKzdIcUh3ClJMV2Ix
    aEdjSE5yNnp0VDRpWkVGRi9neEUrMWREZithb25FQmxpcDA2Y3FlK3l4SElQYXE2MkJWTURIQXhT
    OGwKWWlLOUdGRmdPUHRZNmxMZ0lRUjVERS9XSWZYOVBrL3NWMjFNWjFOdFVFQUVJRHdtRXYzcTRV
    WStrNWdkd3ovdApIa1FnRGZKbmtVMkQzZlZET2dNaE9PMWNhMURyTDMrWDhoaVJhYm9ucnRGWncz
    UWloT3htSFBSWTFUaUFCNnlWClcwa3VoK2Z4QWdNQkFBRUNnZ0VBRGx0dThrMXFURkxoSmdzWFd4
    VEZBQWUrUEJnZkNUMld1YVJNMlNvK3FxakIKMTJPZjBNaWVZUHQ1aGJLNjNIYUMzbmZIZ3FXdDd5
    UGh1bHBYZk9INDVDOEljZ01YbDkzTU1nME1KcjU4bGVNSQorMm9qRnJJcmVySFNGbTVSMVR4d0RF
    d3JWbS9tTW93ekRXRnRRQ2M2elBKOHdObjVSdVA0OEhLZlRaMy8yZmp3CnpFalN3UE8yd0ZNZm8x
    RUpOVGpsSTMwM2xGYmRGQnM2N05hWDZwdWgzME03VG4rZ3puSEt5TzVhN0Y1N3drSXQKZmtnbkV5
    L3NnTWVkUWx3WDdiUnBVb0Q2ZjBmWnpWOFF6NGNIRnl3dFlFcmN6WkpoM1ZHaXRKb08vVkNJRGR0
    eQpSUFhPQXFWRGQ3RXBQMVVVZWhabEtWV1owT1pNRWZSZ0tiUkNlbDVhYlFLQmdRRHdnd3JJUTUr
    QmladjZhMFZUCkVUZVhCK2hSYnZCaW5SeWtOby9SdkxjM2oxZW5SaDkvek8vU2hhZFpJWGdPQWlN
    MUpucjVHcDhLa05HY2E2SzEKbXlodGFkN3hZUE9EWXpOWFhwNlQxT1BnWnhIWkxJWXpWVWo2eXBY
    ZVY2NFRlNVppRGFKMUQ0OWN6c3ErUHFzUQpYUmNnQkpTTnBGdERGaVhXcGpYV2Z4OFB4d0tCZ1FE
    aEFuTFk1U2wyZWVRbyt1ZDBNdmp3ZnRCL21OMnFDekpZCjVBbFFwUkk0VGhXeEpnR1B1SFRSMjl6
    VmE1aVdOWXVBNUxXckMxeS93eCt0NUhLVXdxKzVreHZzK25wWXBESkQKWlgvdzBHbGM2czBKYy9t
    RnlTa2J3OUIyTGVQZWRMN2xSRjVPaUF5QzZEMTA2U2M5VjJqbEw0SWZsbU96dDRDRApaVE5iTHRD
    Nmh3S0JnSGZJekJYeGwvOXNDY011cWRnMU92cDlkYmNaQ2FBVG43QXBmSGQ1QmNjbUhRR3lhdjI3
    Cms3WEYyeE1KR0VIaHpxY3FBeFVOclNnVitFOXZUQm9tckh2UnZyZDVFYzdlR1RQcWJCQTBkMG5N
    QzVlZUZUaDcKd1YwbWlIMjBMWDZHanQ5RzZ5SmlIWVNiZVY1RzErdk9jVFlCRWZ0NVgvcUpqVTdh
    ZVBYYldoMEJBb0dCQUpsVgo1dGdDQ3VodkZsb0s2ZkhZenFadGRUNk8rUGZwVzIwU01Ycmdrdk1G
    MjJoMll2Z0RGckR3cUtSVUI0N05mSHpnCjN5QnB4TkgxY2NBNS93OTdRTzh3M2dYM2g2cWljcEpW
    T0FQdXN1NmNJQkFDRlpmalJ2MWh5c3pPWnd2dytTb2EKRmo1a0hrcVRZMVlwa1JFUFlTOVYyZElX
    MVdqaWMxU1hnWkR3N1ZNL0FvR0FQL2NaM1pIVFNDRFRGbEl0cXk1QwpySXkyQWlZMFdKc3grSzBx
    Y3Z0b3NQT093dG5HaldIYjFnZGFWZGZYL0lSa1NzWDRQQU9kbnN5aWROQzUvbC9tCnk4b2ErNVdF
    ZUdGY2xXRmhyNGRuVEE3NjZvOEhyTTJVaklnV1dZQkYyVktkcHRHbkh4RmVKV0ZVbWVRQy94ZVcK
    dzM3cENTN3lrTCs3Z3A3VjBXU2hZc3c9Ci0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K
